apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-frontend
  labels:
    app: inventory-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-frontend
  template:
    metadata:
      labels:
        app: inventory-frontend
    spec:
      containers:
      - name: inventory-frontend
        image: inventory-frontend:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"